from django.conf.urls import patterns, include, url
from django.views.generic.base import *
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'mysite.talk_cloud_views.talk_cloud_login', name = 'index'),
    #url(r'^(?P<path>.*\..*)$$', 'django.views.static.serve',{'document_root':'static/'}),
    #url(r'^login/$','mysite.views.login', name = 'login'),
    url(r'^action/$','mysite.actions.home', name='action'),
    url(r'^callback/$', 'mysite.views.callback', name = 'callback'),
    url(r'^landing/$', 'mysite.views.LandingPage', name = 'LandingPage'),
    url(r'^landing2/$', 'mysite.views.LandingPage2', name = 'LandingPage'),
    url(r'^landing_mobile/$', 'mysite.views.LandingMobilePage', name = 'LandingMobilePage'),
    
    #url(r'^wx3a6ed5af1b0f81d6/callback$', 'mysite.wechat.home',{'token': '1000000'}),
    url(r'^(?P<token>wx(\d|[a-f]){16})/callback$',  'mysite.wechat.home'),
    url(r'^tsaiServer/webcallback$',  'mysite.tsaiServer.home'),
    url(r'^wxJSWeb/(?P<page>.*)','mysite.tsaiServer.wxJSWeb'),                  
                       
    url(r'^deny', 'mysite.deny.home', name = 'deny'),
    url(r'^wechat/(?P<token>\d{7})$','mysite.wechat.home', name= 'wechat'),
    #url(r'^PayBill/$', 'mysite.views.PayBill', name = 'PayBill'),
    url(r'^PaidCallback$', 'mysite.views.PaidCallback',name = 'PaidCallback'),
    url(r'^RefundCallback$', 'mysite.views.RefundCallback',name = 'RefundCallback'),
    #url(r'^PayDone$', 'mysite.views.PayDone', name = 'PayDone'),
    # url(r'^mysite/', include('mysite.foo.urls')),
    url(r'^polls/', include('polls.urls')),
	url(r'^upload/$','mysite.views.upload', name = 'upload'),

    url(r'^wechartWithdraw/$','mysite.Pay.wechartWithdraw',name = 'wechartWithdraw'),
                       
	#url(r'^wxLogin/$', 'mysite.views.wxLogin', name = 'wxLogin'),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^dailytemplates/$','mysite.views.DailyTemplates',name = 'DailyTemplates'),
    url(r'^functiontest/$', 'mysite.views.FunctionTest', name = 'functiontest'),
    url(r'^updatelessons/$', 'mysite.views.UpdateLessonRelation', name = 'UpdateLessonRelation'),
    #url(r'^SignupTemplateMseeage/$', 'mysite.views.SignupTemplateMseeage', name = 'SignupTemplateMseeage'),
    url(r'^thirdpartylessons/$', 'mysite.views.GetThirdPartyLessons', name = 'GetThirdPartyLessons'),
                       
                       
    url(r'^mainpage/$', 'mysite.dashboard_views.MainPage', name = 'MainPage'),
    url(r'^channelclassdata/$', 'mysite.dashboard_views.ChannelClassPercentageData', name = 'channelclassdata'),
    url(r'^channelclasstimelinedata/$', 'mysite.dashboard_views.ChannelClassTimeLineData', name = 'channelclasstimelinedata'),
    url(r'^newusercomparisondata/$', 'mysite.dashboard_views.NewUserComparisonData', name = 'NewUserComparisonData'),
    url(r'^lessontop10data/$', 'mysite.dashboard_views.LessonTop10Data', name = 'LessonTop10Data'),
    url(r'^newuserpercentdata/$', 'mysite.dashboard_views.NewUserPercentData', name = 'NewUserPercentData'),
    url(r'^userprovincepercentdata/$', 'mysite.dashboard_views.UserProvincePercentData', name = 'UserProvincePercentData'),
    url(r'^newuserprovincepercentdata/$', 'mysite.dashboard_views.NewUserProvincePercentData', name = 'NewUserProvincePercentData'),
    url(r'^tradecategoryrate/$', 'mysite.dashboard_views.TradeCategoryRate', name = 'TradeCategoryRate'),
                       
    url(r'^salespage/$', 'mysite.sales_views.SalesPage', name = 'SalesPage'),
    url(r'^salesstatisticsdata/$', 'mysite.sales_views.SalesStatisticsData', name = 'SalesStatisticsData'),
    url(r'^tradesdata/$', 'mysite.sales_views.TradesData', name = 'TradesData'),
    url(r'^getcategories/$', 'mysite.sales_views.GetCategories', name = 'GetCategories'),
                       
    url(r'^studentpage/$', 'mysite.student_views.StudentPage', name = 'studentpage'),
    url(r'^studentlist/$', 'mysite.student_views.StudentList', name = 'studentlist'),
    url(r'^studenttrade/$', 'mysite.student_views.StudentTrade', name = 'StudentTrade'),
    url(r'^studentdetail/$', 'mysite.student_views.StudentDetail', name = 'StudentDetail'),
    url(r'^sendverificationcode1/$', 'mysite.student_views.SendVerificationCode', name = 'SendVerificationCode'),
    url(r'^VerifyCode/$', 'mysite.student_views.VerifyCode', name = 'VerifyCode'),
    url(r'^getProvince/$', 'mysite.student_views.GetProvince', name = 'GetProvince'),
    url(r'^exportstudents/$', 'mysite.student_views.ExportStudents', name = 'ExportStudents'),
    url(r'^SetCampaignUser/$','mysite.student_views.SetCampaignUser',name = 'SetCampaignUser'),
    url(r'^user_contract/$', 'mysite.student_views.user_contract', name = 'user_contract'),
    url(r'^uploadstudent/$', 'mysite.student_views.UploadStudent', name = 'UploadStudent'),
    url(r'^ClearDailySendTimes/$', 'mysite.student_views.ClearDailySendTimes', name = 'ClearDailySendTimes'),
    url(r'^checkdownloaduser/$', 'mysite.student_views.CheckDownloadUser', name = 'CheckDownloadUser'),
    url(r'^traderefund/$', 'mysite.student_views.TradeRefund', name = 'TradeRefund'),
    
    url(r'^UpdateYouzanCoupons/$', 'mysite.coupon_views.UpdateYouzanCoupons', name = 'UpdateYouzanCoupons'),
    url(r'^GetAllCoupons/$', 'mysite.coupon_views.GetAllCoupons', name = 'GetAllCoupons'),
    url(r'^couponpage/$', 'mysite.coupon_views.CouponPage', name = 'CouponPage'),
    url(r'^UpdateCouponUrl/$', 'mysite.coupon_views.UpdateCouponUrl', name = 'UpdateCouponUrl'),
    url(r'^saveusercoupons/$', 'mysite.coupon_views.SaveUserCoupons', name = 'SaveUserCoupons'),
    url(r'^getallusercoupons/$', 'mysite.coupon_views.GetAllUserCoupons', name = 'GetAllUserCoupons'),
                       
    url(r'^addtag/$', 'mysite.tag_views.AddTag', name = 'AddTag'),
    url(r'^updatetag/$', 'mysite.tag_views.UpdateTag', name = 'UpdateTag'),
    url(r'^deletetag/$', 'mysite.tag_views.DeleteTag', name = 'DeleteTag'),
    url(r'^tagpage/$', 'mysite.tag_views.TagPage', name = 'TagPage'),
    url(r'^gettags/$', 'mysite.tag_views.GetTags', name = 'GetTags'),
    url(r'^setusertags/$', 'mysite.tag_views.SetUserTags', name = 'SetUserTags'),
    url(r'^deleteusertags/$', 'mysite.tag_views.DeleteUserTags', name = 'DeleteUserTags'),
    url(r'^setconditiontag/$', 'mysite.tag_views.SetConditionTag', name = 'SetConditionTag'),
    url(r'^autotags/$', 'mysite.tag_views.AutoTags', name = 'AutoTags'),
                       
                       
    url(r'^importdetailpage/$', 'mysite.import_views.ImportDetailPage', name = 'importdetailpage'),
    url(r'^importdetaillist/$', 'mysite.import_views.ImportDetailList', name = 'importdetaillist'),
	url(r'^updatetrades/$', 'mysite.import_views.UpdateThirdPartyTrades', name = 'updatetrades'),
    url(r'^import_test/$', 'mysite.import_views.import_test', name = 'import_test'),
    url(r'^update_edusoho_user/$', 'mysite.import_views.UpdateEdusohoUser', name = 'UpdateEdusohoUser'),
    url(r'^update_edusoho_order/$', 'mysite.import_views.UpdateEdusohoOrder', name = 'UpdateEdusohoOrder'),
    url(r'^UpdateUserAndTradesFromEdusoho/$', 'mysite.import_views.UpdateUserAndTradesFromEdusoho', name = 'UpdateUserAndTradesFromEdusoho'),
    url(r'^UpdateThirdParytID/$', 'mysite.import_views.UpdateThirdParytID', name = 'UpdateThirdParytID'),
    url(r'^UpdateThirdParytLessons/$', 'mysite.import_views.UpdateThirdParytLessons', name = 'UpdateThirdParytLessons'),
    url(r'^UpdateLessonCategory/$', 'mysite.import_views.UpdateLessonCategory', name = 'UpdateLessonCategory'),
    url(r'^UpdateTradeCategory/$', 'mysite.import_views.UpdateTradeCategory', name = 'UpdateTradeCategory'),
                       
                       
    url(r'^templatepage/$', 'mysite.template_views.TemplatePage', name = 'TemplatePage'),
    url(r'^templatelist/$', 'mysite.template_views.TemplateList', name = 'TemplateList'),
    url(r'^getaccounttemplates/$', 'mysite.template_views.GetAccountTemplates', name = 'GetAccountTemplates'),
    url(r'^SendTemplateMessage/$', 'mysite.template_views.SendTemplateMessage', name = 'SendTemplateMessage'),
    url(r'^getmessageinfo/$', 'mysite.template_views.GetMessageInfo', name = 'GetMessageInfo'),
    url(r'^msginfopage/$', 'mysite.template_views.MsgInfoPage', name = 'MsgInfoPage'),
    url(r'^TemplateMsgTask/$', 'mysite.template_views.TemplateMsgTask', name = 'TemplateMsgTask'),
    url(r'^UpdateTemplateSendResult/$', 'mysite.template_views.UpdateTemplateSendResult', name = 'UpdateTemplateSendResult'),
    url(r'^telmessagepage/$', 'mysite.template_views.TelMessagePage', name = 'TelMessagePage'),
    url(r'^gettelmsgtemplates/$', 'mysite.template_views.GetTelMsgTemplates', name = 'GetTelMsgTemplates'),
    url(r'^updatetelmsgtemplates/$', 'mysite.template_views.UpdateTelMsgTemplates', name = 'UpdateTelMsgTemplates'),
    
    url(r'^wxLoginRedirect/$', 'mysite.views.wxLoginRedirect', name = 'wxLoginRedirect'),
                       
    url(r'^setthirdpartylesson/$', 'mysite.views.setThirdPartyLessonID', name = 'setThirdPartyLessonID'),                   
    url(r'^functiontest/$', 'mysite.views.FunctionTest', name = 'functiontest'),
    
    url(r'^campaignpage/$', 'mysite.campaign_views.CampaignPage', name = 'CampaignPage'),
    url(r'^getcampaigns/$', 'mysite.campaign_views.GetCampaigns', name = 'GetCampaigns'),
    url(r'^savecampaign/$', 'mysite.campaign_views.SaveCampaign', name = 'SaveCampaign'),
    url(r'^deletecampaign/$', 'mysite.campaign_views.DeleteCampaign', name = 'DeleteCampaign'),
                       
                       
                       
    url(r'^GetQRCode/$', 'mysite.talk_cloud_views.GetQRCode', name = 'GetQRCode'),
    url(r'^GetScanUser/$', 'mysite.talk_cloud_views.GetScanUser', name = 'GetScanUser'),
    url(r'^talk_cloud_login/$', 'mysite.talk_cloud_views.talk_cloud_login', name = 'talk_cloud_login'),
    url(r'^talk_cloud_create_class/$', 'mysite.talk_cloud_views.talk_cloud_create_class', name = 'talk_cloud_create_class'),
    url(r'^talk_cloud_courses/$', 'mysite.talk_cloud_views.talk_cloud_courses', name = 'talk_cloud_courses'),
    url(r'^loginverifycode/$', 'mysite.talk_cloud_views.LoginVerifyCode', name = 'LoginVerifyCode'),
    url(r'^getcourseuserinfo/$', 'mysite.talk_cloud_views.GetUserInfo', name = 'GetUserInfo'),
    url(r'^GetUserLessons/$', 'mysite.talk_cloud_views.GetUserLessons', name = 'GetUserLessons'),
                       
    url(r'^courseschedulepage/$', 'mysite.cloud_course_lesson_views.CourseSchedulePage', name = 'CourseSchedulePage'),
    url(r'^getcloudcourses/$', 'mysite.cloud_course_lesson_views.GetCloudCourses', name = 'GetCloudCourses'),
    url(r'^getcourselesson/$', 'mysite.cloud_course_lesson_views.GetCourseLesson', name = 'GetCourseLesson'),
    url(r'^UpdateCourseLesson/$', 'mysite.cloud_course_lesson_views.UpdateCourseLesson', name = 'UpdateCourseLesson'),
    url(r'^HourlyClassRemind/$', 'mysite.cloud_course_lesson_views.HourlyClassRemind', name = 'HourlyClassRemind'),
    url(r'^LessonRemindASYNC/$', 'mysite.cloud_course_lesson_views.LessonRemindASYNC', name = 'LessonRemindASYNC'),
    url(r'^DailyClassRemind/$', 'mysite.cloud_course_lesson_views.DailyClassRemind', name = 'DailyClassRemind'),
    url(r'^uploadcourse/$', 'mysite.cloud_course_lesson_views.UploadCourse', name = 'UploadCourse'),
    #url(r'^uploadcourse/$', 'mysite.cloud_course_lesson_views.UploadUsers', name = 'UploadUsers'),
    url(r'^updatecoursememberbydate/$', 'mysite.cloud_course_lesson_views.UpdateCourseMemberByDate', name = 'UpdateCourseMemberByDate'),
    
    url(r'^courseclasspage/$', 'mysite.cloud_course_class_views.CourseClassPage', name = 'CourseClassPage'),
    url(r'^getcloudcoursesforclass/$', 'mysite.cloud_course_class_views.GetCloudCoursesForClass', name = 'GetCloudCoursesForClass'),
    url(r'^divideclass/$', 'mysite.cloud_course_class_views.DivideClass', name = 'DivideClass'),
    url(r'^getcloudcourseclasses/$', 'mysite.cloud_course_class_views.GetCloudCourseClasses', name = 'GetCloudCourseClasses'),
    url(r'^getcloudcourseclassmember/$', 'mysite.cloud_course_class_views.GetCloudCourseClassMember', name = 'GetCloudCourseClassMember'),
    url(r'^clearclasses/$', 'mysite.cloud_course_class_views.ClearClasses', name = 'ClearClasses'),
    url(r'^uploadclasses/$', 'mysite.cloud_course_class_views.UploadClasses', name = 'UploadClasses'),
    url(r'^addstudenttoclass/$', 'mysite.cloud_course_class_views.AddStudentToClass', name = 'AddStudentToClass'),
    url(r'^removestudentfromclass/$', 'mysite.cloud_course_class_views.RemoveStudentFromClass', name = 'RemoveStudentFromClass'),
    url(r'^addstudenttocourse/$', 'mysite.cloud_course_class_views.AddStudentToCourse', name = 'AddStudentToCourse'),
    url(r'^removestudentfromcourse/$', 'mysite.cloud_course_class_views.RemoveStudentFromCourse', name = 'RemoveStudentFromCourse'),
    url(r'^updateclassinfo/$', 'mysite.cloud_course_class_views.UpdateClassInfo', name = 'UpdateClassInfo'),
    url(r'^getcloudcoursemembernotinclass/$', 'mysite.cloud_course_class_views.GetCloudCourseMemberNotInClass', name = 'GetCloudCourseMemberNotInClass'),
    url(r'^getcloudcoursemember/$', 'mysite.cloud_course_class_views.GetCloudCourseMember', name = 'GetCloudCourseMember'),
    url(r'^getteachers/$', 'mysite.cloud_course_class_views.GetTeachers', name = 'GetTeachers'),
    url(r'^exportcourseclass/$', 'mysite.cloud_course_class_views.ExportCourseClass', name = 'ExportCourseClass'),
    url(r'^uploadteacher/$', 'mysite.cloud_course_class_views.UploadTeacher', name = 'UploadTeacher'),
    url(r'^updatemember/$', 'mysite.cloud_course_class_views.UpdateMember', name = 'UpdateMember'),
                       
    url(r'^courseclassroompage/$', 'mysite.cloud_course_classroom_views.CourseClassroomPage', name = 'CourseClassroomPage'),                   
    url(r'^getclassrooms/$', 'mysite.cloud_course_classroom_views.GetClassrooms', name = 'GetClassrooms'),
    url(r'^ClassStart/$', 'mysite.cloud_course_classroom_views.ClassStart', name = 'ClassStart'),
    url(r'^ClassEnd/$', 'mysite.cloud_course_classroom_views.ClassEnd', name = 'ClassEnd'),
    url(r'^HourlyStartClassRoom/$', 'mysite.cloud_course_classroom_views.HourlyStartClassRoom', name = 'HourlyStartClassRoom'),
    url(r'^deleteclassroom/$', 'mysite.cloud_course_classroom_views.DeleteClassroom', name = 'DeleteClassroom'),
                       
    url(r'^coursewarepage/$', 'mysite.cloud_course_ware_views.coursewarepage', name = 'coursewarepage'),                   
    url(r'^getcourseware/$', 'mysite.cloud_course_ware_views.GetCourseWare', name = 'GetCourseWare'),
    url(r'^uploadfile/$', 'mysite.cloud_course_ware_views.UploadFile', name = 'UploadFile'),
    url(r'^deletefile/$', 'mysite.cloud_course_ware_views.DeleteFile', name = 'DeleteFile'),
    url(r'^connectfile/$', 'mysite.cloud_course_ware_views.ConnectFile', name = 'ConnectFile'),
    
    url(r'^getchannelsanddistributors/$', 'mysite.channel_views.GetChannelsAndDistributors', name = 'GetChannelsAndDistributors'),
    url(r'^getchannelswitheditable/$', 'mysite.channel_views.GetChannelsWithEditable', name = 'GetChannelsWithEditable'),
    url(r'^channelpage/$', 'mysite.channel_views.ChannelPage', name = 'ChannelPage'),
    url(r'^savechannel/$', 'mysite.channel_views.SaveChannel', name = 'SaveChannel'),
    url(r'^deletechannel/$', 'mysite.channel_views.DeleteChannel', name = 'DeleteChannel'),url(r'^deletechannel/$', 'mysite.channel_views.DeleteChannel', name = 'DeleteChannel'),
                       
    url(r'^lessonpage/$', 'mysite.lesson_views.LessonPage', name = 'LessonPage'),
    url(r'^thirdpartylessonpage/$', 'mysite.lesson_views.ThirdPartyLessonPage', name = 'ThirdPartyLessonPage'),
    url(r'^getcatetories/$', 'mysite.lesson_views.GetCatetories', name = 'GetCatetories'),
    url(r'^getlessons/$', 'mysite.lesson_views.GetLessons', name = 'GetLessons'),
    url(r'^savelesson/$', 'mysite.lesson_views.SaveLesson', name = 'SaveLesson'),
    url(r'^deletelesson/$', 'mysite.lesson_views.DeleteLesson', name = 'DeleteLesson'),
    url(r'^getthirdpartylessons/$', 'mysite.lesson_views.GetThirdPartyLessons', name = 'GetThirdPartyLessons'),
    url(r'^savethirdpartylesson/$', 'mysite.lesson_views.SaveThirdPartyLesson', name = 'SaveThirdPartyLesson'),
    url(r'^deletethirdpartylesson/$', 'mysite.lesson_views.DeleteThirdPartyLesson', name = 'DeleteThirdPartyLesson'),
    url(r'^getlessonmapping/$', 'mysite.lesson_views.GetLessonMapping', name = 'GetLessonMapping'),
    url(r'^getlessonmappingnew/$', 'mysite.lesson_views.GetLessonMappingNew', name = 'GetLessonMappingNew'),
    url(r'^relatelesson/$', 'mysite.lesson_views.RelateLesson', name = 'RelateLesson'),
    url(r'^deleterelation/$', 'mysite.lesson_views.DeleteRelation', name = 'DeleteRelation'),
                       
    url(r'^productpage/$', 'mysite.product_views.ProductPage', name = 'ProductPage'),
    url(r'^getproducts/$', 'mysite.product_views.GetProducts', name = 'GetProducts'),
    url(r'^getproducttypes/$', 'mysite.product_views.GetProductTypes', name = 'GetProductTypes'),
    url(r'^saveproduct/$', 'mysite.product_views.SaveProduct', name = 'SaveProduct'),
    url(r'^putawayproduct/$', 'mysite.product_views.PutawayProduct', name = 'PutawayProduct'),
    url(r'^takeoffproduct/$', 'mysite.product_views.TakeOffProduct', name = 'TakeOffProduct'),
    url(r'^getproductmessagetypes/$', 'mysite.product_views.GetProductMessageTypes', name = 'GetProductMessageTypes'),
    url(r'^getproductmessages/$', 'mysite.product_views.GetProductMessages', name = 'GetProductMessages'),
    url(r'^UpdateProductMessage/$', 'mysite.product_views.UpdateProductMessages', name = 'UpdateProductMessages'),
    url(r'^getallproducttags/$', 'mysite.product_views.GetAllProductTags', name = 'GetAllProductTags'),
    url(r'^getproducttags/$', 'mysite.product_views.GetProductTagsByID', name = 'GetProductTagsByID'),
    url(r'^saveproducttags/$', 'mysite.product_views.SaveProductTags', name = 'SaveProductTags'),
    url(r'^deleteproducttag/$', 'mysite.product_views.DeleteProductTag', name = 'DeleteProductTag'),
    url(r'^getproductputawaychannels/$', 'mysite.product_views.GetProductPutawayChannels', name = 'GetProductPutawayChannels'),
                       
    url(r'^clearuserovertimepoints/$', 'mysite.point_views.ClearUserOvertimePoints', name = 'ClearUserOvertimePoints'),
    url(r'^clearovertimepoints/$', 'mysite.point_views.ClearOvertimePoints', name = 'ClearOvertimePoints'),
    url(r'^sendovertimemsg/$', 'mysite.point_views.SendOvertimeMsg', name = 'SendOvertimeMsg'),
    url(r'^senduserovertimemessage/$', 'mysite.point_views.SendUserOvertimeMsg', name = 'SendUserOvertimeMsg'),
    
                       
    # WeChat MiniApp APIs
    url(r'^MiniAppAPI/wechatpay/$', 'mysite.miniapp.wechatPay', name = 'wechatPay'),
    url(r'^MiniAppAPI/wxprepayid/$', 'mysite.miniapp.wxPrepayId', name = 'wxPrepayId'),
    url(r'^MiniAppAPI/wechatprepay/$', 'mysite.miniapp.wechatPrepay', name = 'wechatPrepay'),
    url(r'^MiniAppAPI/wechatopenid/$', 'mysite.miniapp.wechatOpenId', name = 'wechatOpenId'),
    url(r'^MiniAppAPI/wechatprepaywithopenid/$', 'mysite.miniapp.wechatPrepayWithOpenId', name = 'wechatPrepayWithOpenId'),
	url(r'^MiniAppAPI/wechatupdateuser/$', 'mysite.miniapp.UpdateUserInfo', name = 'wechatUpdateUser'),
    url(r'^MiniAppAPI/getuserinfo/$','mysite.miniapp.GetUserInfo',name = 'getUserInfo'),
    url(r'^MiniAppAPI/updateformid/$','mysite.miniapp.UpdateFormid',name = 'updateFormid'),
    url(r'^MiniAppAPI/testfunction/$','mysite.miniapp.TestFunction',name = 'TestFunction'),
    url(r'^MiniAppAPI/getminiappproducts/$', 'mysite.miniapp.GetMiniappProducts', name = 'GetMiniappProducts'),
    url(r'^MiniAppAPI/getminiappproductdetail/$', 'mysite.miniapp.GetMiniappProductDetail', name = 'GetMiniappProductDetail'),
    url(r'^MiniAppAPI/wechatprepaywithproductid/$', 'mysite.miniapp.WechatPrepayWithProductId', name = 'WechatPrepayWithProductId'),
    url(r'^MiniAppAPI/createorder/$', 'mysite.miniapp.CreateOrder', name = 'CreateOrder'),
    url(r'^MiniAppAPI/getorderlist/$', 'mysite.miniapp.GetOrderList', name = 'GetOrderList'),
    url(r'^MiniAppAPI/cancelorder/$', 'mysite.miniapp.CancelOrder', name = 'CancelOrder'),
    #url(r'^miniappteacherpage/$', 'mysite.miniapp.MiniappTeacherPage', name = 'MiniappTeacherPage'),
    #url(r'^MiniAppAPI/getminiappteachers/$', 'mysite.miniapp.GetMiniappTeachers', name = 'GetMiniappTeachers'),
    #url(r'^MiniAppAPI/getteachers/$', 'mysite.miniapp.GetTeachers', name = 'GetTeachers'),
    #url(r'^MiniAppAPI/saveminiappteacher/$', 'mysite.miniapp.SaveMiniappTeacher', name = 'SaveMiniappTeacher'),
    #url(r'^MiniAppAPI/deleteminiappteacher/$', 'mysite.miniapp.DeleteMiniappTeacher', name = 'DeleteMiniappTeacher'),
    url(r'^MiniAppAPI/getbannerlist/$', 'mysite.miniapp.GetBannerList', name = 'GetBannerList'),
    url(r'^MiniAppAPI/getheatminiappproducts/$', 'mysite.miniapp.GetHeatMiniappProducts', name = 'GetHeatMiniappProducts'),
    url(r'^MiniAppAPI/getminiappproductsbycategory/$', 'mysite.miniapp.GetMiniappProductsByCategory', name = 'GetMiniappProductsByCategory'),
    url(r'^MiniAppAPI/getcategories/$', 'mysite.miniapp.GetCategories', name = 'GetCategories'),
    url(r'^MiniAppAPI/custommessage/$', 'mysite.miniapp.CustomMessage', name = 'CustomMessage'),
    url(r'^MiniAppAPI/getminiappuserinfo/$', 'mysite.miniapp.GetMiniappUserInfo', name = 'GetMiniappUserInfo'),
    url(r'^MiniAppAPI/orderrefund/$', 'mysite.miniapp.OrderRefund', name = 'OrderRefund'),
    url(r'^MiniAppAPI/getposter/$', 'mysite.miniapp.GetPoster', name = 'GetPoster'),
    url(r'^MiniAppAPI/getuserpoints/$', 'mysite.miniapp.GetUserPoints', name = 'GetUserPoints'),
    url(r'^MiniAppAPI/getuserpointdetail/$', 'mysite.miniapp.GetUserPointDetails', name = 'GetUserPointDetails'),
    url(r'^MiniAppAPI/getorderinfo/$', 'mysite.miniapp.GetOrderInfo', name = 'GetOrderInfo'),
    url(r'^MiniAppAPI/payorder/$', 'mysite.miniapp.PayOrder', name = 'PayOrder'),
    url(r'^getbindingqrcode/$', 'mysite.miniapp.GetBindingQRCode', name = 'GetBindingQRCode'),
    url(r'^MiniAppAPI/saveuserbuymessages/$', 'mysite.miniapp.SaveUserBuyMessages', name = 'SaveUserBuyMessages'),
    url(r'^MiniAppAPI/getuserbuymessages/$', 'mysite.miniapp.GetUserBuyMessages', name = 'GetUserBuyMessages'),
    url(r'^MiniAppAPI/setuserdefaultmessage/$', 'mysite.miniapp.SetUserDefaultMessage', name = 'SetUserDefaultMessage'),
    url(r'^MiniAppAPI/getcampaingpage/$','mysite.miniapp.GetCampaingPage',name = 'GetCampaingPage'),
    url(r'^MiniAppAPI/getcashbackpage/$','mysite.miniapp.GetCashbackPage',name = 'GetCashbackPage'),
    url(r'^update_wechat_order/$','mysite.miniapp.update_wechat_order',name = 'update_wechat_order'),
    url(r'^update_wechat_product/$','mysite.miniapp.update_wechat_product',name = 'update_wechat_product'),
    url(r'^update_wechat_cart/$','mysite.miniapp.update_wechat_cart',name = 'update_wechat_cart'),
                       
                       
    url(r'^miniappcampaignpage/$','mysite.miniapp_campaign_views.MiniappCampaignPage',name = 'MiniappCampaignPage'),
    url(r'^getminiappcampaignbanner/$','mysite.miniapp_campaign_views.GetMiniappCampaignBanner',name = 'GetMiniappCampaignBanner'),
    url(r'^saveminiappcampaignbanner/$','mysite.miniapp_campaign_views.SaveMiniappCampaignBanner',name = 'SaveMiniappCampaignBanner'),
    url(r'^getminiappcampaigntags/$','mysite.miniapp_campaign_views.GetMiniappCampaignTags',name = 'GetMiniappCampaignTags'),
    url(r'^updateminiappcampaigntags/$','mysite.miniapp_campaign_views.UpdateMiniappCampaignTags',name = 'UpdateMiniappCampaignTags'),
    url(r'^getminiappcampaigntagproducts/$','mysite.miniapp_campaign_views.GetMiniappCampaignTagProducts',name = 'GetMiniappCampaignTagProducts'),
    url(r'^getminiappcampaigntagnewproducts/$','mysite.miniapp_campaign_views.GetMiniappCampaignTagNewProducts',name = 'GetMiniappCampaignTagNewProducts'),
    url(r'^deleteminiappcampaigntagproducts/$','mysite.miniapp_campaign_views.DeleteMiniappCampaignTagProducts',name = 'DeleteMiniappCampaignTagProducts'),
    url(r'^addminiappcampaigntagproducts/$','mysite.miniapp_campaign_views.AddMiniappCampaignTagProducts',name = 'AddMiniappCampaignTagProducts'),
    url(r'^deleteminiappcampaigntag/$','mysite.miniapp_campaign_views.DeleteMiniappCampaignTag',name = 'DeleteMiniappCampaignTag'),
    
)

# Serve static files for admin, use this for debug usage only
# `python manage.py collectstatic` is preferred.
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

